name: Daily Workflow

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name to pull the image from'
        required: true
        default: 'master'
jobs:
  daily-workflow:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doruirimescu/python-trading:${{ github.event.inputs.branchName }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'python-trading' # Checkout the repository into the 'app' directory

      - name: Create .env file
        run: |
          cd python-trading
          touch Trading/config/.env
          touch Trading/utils/.env

          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> Trading/config/.env
          echo 'EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}' >> Trading/config/.env
          echo 'EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}' >> Trading/config/.env

          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> Trading/utils/.env
          echo 'EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}' >> Trading/utils/.env
          echo 'EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}' >> Trading/utils/.env

      - name: Run daily scripts
        run: |
          cd python-trading
          ls -la
          bash script/daily_workflow.sh
          python3 script/daily_workflow.py

      - name: Commit and push changes
        run: |
          cd python-trading
          ls -la
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .
          git commit -m "Add generated workflow files"
          git push https://${{ secrets.MY_PAT }}@github.com/doruirimescu/python-trading HEAD:${{ github.event.inputs.branchName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
