name: Run Email Test

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name to pull the image from'
        required: true
        default: 'master'
jobs:
  test-email:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doruirimescu/python-trading:${{ github.event.inputs.branchName }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: '/usr/src/app' # Checkout the repository into the 'app' directory

      - name: Create .env file
        run: |
          cd /usr/src/app
          touch Trading/config/.env
          touch Trading/utils/.env

          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> Trading/config/.env
          echo 'EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}' >> Trading/config/.env
          echo 'EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}' >> Trading/config/.env

          echo 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' >> Trading/utils/.env
          echo 'EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}' >> Trading/utils/.env
          echo 'EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}' >> Trading/utils/.env

      - name: Run test script
        run: |
          cd /usr/src/app
          ls -la
          python3 script/daily_workflow.py
          touch test.txt
          echo "generated text" >> test.txt

      - name: Commit and push changes
        run: |
          cd /usr/src/app
          git config --global user.name '${{ github.actor }}'
          git add test.txt
          git commit -m "Add generated workflow files"
          git push origin HEAD:${{ github.event.inputs.branchName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
